id: ADBD1DD4C
title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru from
  Afar'
type: translation
pechas:
- I681C1437
- I4F4EFC04
- IDD3D2235
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:39.634027
  last_modified_at: 2023-01-04 11:47:39.634036
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I681C1437/637C: 92AC
  I4F4EFC04/DAFB: 92AC
  IDD3D2235/FD18: 92AC
